// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wawztqwoicoixhswtago.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indhd3p0cXdvaWNvaXhoc3d0YWdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NzM0MDUsImV4cCI6MjA2MzA0OTQwNX0.VU_Sw9Vsh7H9swrkxvTRD9skgU9u-VSWvcSLJgVveK8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);